README.md
docs/examples/cla.yaml
docs/examples/prettier.yaml
docs/examples/profanity-filter.yaml
docs/examples/release.yaml
docs/maven-publish-pom-preparation_doc.md
docs/reusable/create-github-release_doc.md
docs/reusable/maven-publish_doc.md
docs/reusable/update-pom-release_doc.md

Added description for maven release workflow and workflow files examples

Added description for maven release workflow

---

.github/workflows/python-publish.yml
.github/workflows/release-drafter.yml
docs/examples/python-release.yaml
docs/examples/upload-to-maven-central.yaml

feat(ci): Add Python release workflowand enhance existing workflows with input parameters

feat(ci): Add Python release workflow

---

.github/workflows/create-github-release.yml
actions/commit-and-push/README.md
actions/commit-and-push/action.yml
actions/poetry-publisher/README.md
actions/poetry-publisher/action.yml

Introduce a Poetry Publisher GitHub Action for automating Python package publishing and enhance the Commit and Push Action with better documentation and features. Clean up formatting and standardize README sections for consistency.

Add GitHub Actions for automated publishing and improved documentation

---

actions/pr-add-messages/action.yaml

Added error handling
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/f9b97635245022dbc77fafefe9e23bcf06be8e42) fix: Update action.yaml
Added error handling

fix: Update action.yaml

---

actions/cdxgen/action.yaml

Generates SBOM file by CDXgen and creates vulnerability report by CycloneDX
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/29ec589b16b0f0ac4ae4af956740506f4cabe5f0) feat: add action to generate SBOM file and vulnerability report for multiple project types
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/9e04c8c2ad0ff2d000f230952410b4868cf19cba) feat: add action to generate SBOM file and vulnerability report for multiple project types
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/b25a751b3dcb2d6f1e1e23a4a9d3f3ade070474b) fix: update JDK setup and Maven build steps in cdxgen action
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/2f225b3d858dfe6c457748afb869aedbf5ca204a) fix: simplify Maven …

feat: Added  new action to generate SBOM files

---

README.md

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/2438d27e72714eb54c8edf307f44c03da0c91b0f) refactor: Refactor maven configuration files for improved clarity and structure
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/f25f4090765400da06cc85f27bd5c5f9c81d2486) fix: Update README.md links to point to the main branch for workflow templates
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/297525df3dd83db54ee3d8999a9a1cf39eb7935a) fix: Update README.md to correct path for auto-labeler configuration file

feat: readme improvement

---

.github/auto-labeler-config.yaml
README.md

[ormig](https://github.com/Netcracker/qubership-workflow-hub/commit/9b2e274a8286e7b66ebc974b7d0a6396496e02b4) fix typos in readme and auto-labeler-config

fix typos in readme and auto-labeler-config

---

actions/cdxgen/action.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/984a9183a71bacd9ffa860e3987fcc669eb0f97b) feat: Update action.yaml
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/183f18c57f0bf462b0955d8c0cfe3d17fd401b56) ci: Update action.yaml
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/c65d522f85a10f8c048cc57896096e4de06a5a28) Update action.yaml
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/68f0849d85ff877ea74b4d71e54fe953b0014177) Update action.yaml
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/3c993e62b1fd2df0bc33a3eebbc7edec48b7e6ca) Update action.yaml
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/bbc9c8cd59d585f25beeaf66a3bdfd99f1dd300d) Update …

feat: added license report to cdxgen

---

.github/workflows/maven-central-snapshot-deploy-reusable.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/8a458f1ac25f93148b10ecaf401e1fb9b0237b19) feat: Add reusable GitHub Actions workflow for Maven Central snapshot deployment

feat: Add reusable GitHub Actions workflow for Maven Central snapshot deployment

---

.github/workflows/docker-publish.yml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/9428d7d7222704ba345b194b41b5c70bead9e5cc) feat: add platforms input to Docker publish workflow
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/41ac0f184476a295b4b2de07001900fc85fd3186) feat: update Docker publish workflow to set up QEMU and use Buildx v3

feat: added platforms to docker-publish

---

.github/workflows/re-pr-assigner.yml
docs/README.md
docs/reusable/pr-assinger.md

Introduce a new workflow for automatically assigning reviewers to pull requests, along with comprehensive documentation on its usage and configuration. Update existing documentation for clarity and accuracy.

feat: Add PR Auto-Assignment workflow and documentation

---

.github/pr-assigner-config.yml
.github/workflows/re-pr-assigner.yml

Enhance the configuration for the PR assigner by including a count for assignees and ensuring proper YAML parsing for accurate retrieval of assignee values.

fix: Update YAML parsing to ensure proper retrieval of assignees and count values

---

.github/linters/.checkov.yaml
.github/linters/.eslintrc.yml
.github/linters/.flake8
.github/linters/.golangci.yml
.github/linters/.jscpd.json
.github/linters/.yaml-lint.yml
.github/linters/actionlint.yml
.github/super-linter.env
.github/workflows/super-linter.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/ba643b91b26c7a5f170acc868fd00ab0690f0757) feat(ci): Update super-linter configuration and add new linters for improved code quality

feat(ci): Update super-linter configuration and add new linters for improved code quality

---

actions/verify-json/README.md
actions/verify-json/action.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/2814fd241f7fbd5b9183a6d214451af587ec4931) feat: add Verify JSON file action with schema validation

feat: add Verify JSON file action with schema validation

---

.github/workflows/cdxgen.yaml
actions/cdxgen/action.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/90d72ca55c8ad214c2cc31604d7da747d2314e02) fix(ci): Remove unused input parameters from cdxgen workflow

fix(ci): Remove unused input parameters from cdxgen workflow

---

.github/workflows/broadcast-files.yml
.github/workflows/cla.yaml
docs/reusable/broadcast-files.md

fix: static branch set to reduce branch creation
feat: several separate jobs added. example configs job configured to use .github repo as config source
fix: main branch set for all jobs. commit message updated
fix: committer email deleted
chore: temp topics set

fix: Broadcast workflow updated with correct branching settings

---

docs/reusable/docker-publish.md
docs/reusable/github-release.md
docs/reusable/maven-publish.md
docs/reusable/python-publish.md
docs/reusable/release-drafter.md
docs/reusable/tag-creator.md

docs: add necessary permissions to job examples.

docs: Added permissions to examples

---

.github/workflows/re-maven-snapshot-deploy.yaml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/2af412a7b35d28d2afca8a89271b1fdbe3287f8a) feat: Add Maven deploy reusable workflow for snapshot artifacts

feat: Add Maven deploy reusable workflow for snapshot artifacts

---

.github/workflows/docker-publish.yml
actions/metadata-action/config.schema.json
actions/metadata-action/dist/config.schema.json
actions/metadata-action/dist/index.js
actions/metadata-action/src/index.js

Improve pattern matching and template filling in the metadata action, update regex patterns for better validation, and add a tags-override input to the Docker publish workflow for increased flexibility.
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/2512bcca5604b9962d5cd40588b84088be9f684a) fix: enhance pattern matching and template filling in metadata action
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/b216ac3a0570c8ca90c2df806853644ecf63b292) fix: improve pattern normalization and template filling in metadata action
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/80ba6fae74dafc79c7c0898835acf4c9abc95794) fix: add tags-override input to Docker publish workflow for enhanced flexibility …

fix: Enhance metadata action and Docker publish workflow

---

docs/maven-publish-pom-preparation_doc.md

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/12e130c35a67339d7fc3ae78270aa695b29a185a) docs: Update maven-publish documentation to include distributionManagement and snapshots repository sections
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/5f322e1665378331855dd2b0807363b51e42aa06) docs(linters): Clarify instructions for mandatory Maven Central properties in documentation

docs: Update maven-publish documentation to include distributionManagement and snapshots repository sections

---

actions/metadata-action/dist/index.js
actions/metadata-action/src/index.js
actions/metadata-action/src/loader.js

Enhance the metadata action by improving error handling for missing configuration files, changing errors to warnings, and refining dist-tag and template retrieval processes. Implement null checks and consistent state management for file existence to ensure more robust functionality. Clarify warning messages for better user understanding.

feat: Improve metadata action error handling and dist-tag management

---

docs/fork-sequence.md

docs: add documentation links into fork sequence document

docs: Update fork-sequence.md

---

.github/workflows/broadcast-files.yml

feat: single repo update option added

---

actions/store-input-params/README.md
actions/store-input-params/action.yaml

[LightlessOne](https://github.com/Netcracker/qubership-workflow-hub/commit/f52e94cab69f2eda1072c6a18dae5f7c61fa7be3) feat: Add 'store-input-params' action

feat: Add 'store-input-params' action

---

actions/metadata-action/config.schema.json
actions/metadata-action/dist/config.schema.json
actions/metadata-action/dist/index.js
actions/metadata-action/src/index.js

fix: Issue with 'dist-tag cant find value from code. Update the schema to reflect the renaming of 'dist-tags' to 'distribution-tag' and remove unused functions for improved code clarity.
#146
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/56556487748b2ae640615edb69dbf2be992b1321) fix: Dist-tag resolve + Rename 'dist-tags' to 'distribution-tag' in schema and update references
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/56ee44cf20ca7f527ade9fae11357a338b73d867) fix: Remove unused functions and clean up code in metadata action
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/8c7c0aed58731dcd431d4b49d21c5c5b4414f5c7) fix: Simplify logging of reference name in run function …

fix: Issue with 'dist-tag cant find value from code. Rename 'dist-tags' to 'distribution-tag' and clean up metadata action

---

actions/helm-charts-release/README.md
actions/helm-charts-release/action.yaml
actions/helm-charts-release/helm-charts-release-config.yaml

Issue #138
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/f371651f570d9e55309f3b6df6e192c2215947a1) feat(ci): #138 Added helm-charts-release action
[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/c28fe6b6c9151065aee4fe7e9b309cd11030554f) docs: Update README.md
Fixed format for Markdown linter .

feat(ci): Added helm-charts-release action

---

actions/custom-event/README.md

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/be56491aeec84252f19e39ccada9518a32ae3383) docs: Update README.md

docs: Update README.md

---

actions/tag-action/action.yml

[borislavr](https://github.com/Netcracker/qubership-workflow-hub/commit/1055f77fedebe8a502870b46eb0af155b823468f) fix: ensure fetch-depth is set for checkout

fix: ensure fetch-depth is set for checkout

---

actions/archive-and-upload-assets/README.md
actions/archive-and-upload-assets/action.yml
actions/archive-and-upload-assets/config.schema.json
actions/archive-and-upload-assets/dist/index.js
actions/archive-and-upload-assets/index.js
actions/archive-and-upload-assets/loader.js
actions/archive-and-upload-assets/package-lock.json
actions/archive-and-upload-assets/package.json

feat: Add new features to the archive and upload action, including enhanced configuration options for files and folders. Remove the `minItems` requirement from the JSON schema for archives and clarify documentation regarding the workflow dispatch trigger.
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/880b6fa94be0d19220a1128479d23f7bb94f91f6) feat: enhance archive and upload action with new features and improved configuration options
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/2965453e32280c8797a1ee92a178cba2fcb4829e) fix: remove minItems requirement from archives in JSON schema and update notes for clarity
[nookyo](https://github.com/Netcracker/qubership-workflow-hub/commit/ee99cc6a3f5b0f2fb6c1748b2f3d802db26ce31d) fix: remove push trigger …

feat: Enhance archive and upload action with improved configuration options

---

actions/container-package-cleanup/README.md
actions/container-package-cleanup/dist/index.js
actions/container-package-cleanup/package-lock.json
actions/container-package-cleanup/package.json
actions/container-package-cleanup/src/index.js
actions/container-package-cleanup/src/report.js
actions/container-package-cleanup/tests/report.test.js
actions/container-package-cleanup/tests/wrapper.test.js

fix: Fix wildcard issue. Switch to Jest for testing, improve logging and package filtering in the code, and add unit tests for key classes. Update README for better clarity on wildcard matching and tag filtering.
https://github.com/Netcracker/qubership-workflow-hub/issues/168

fix: Update testing framework and enhance documentation

---

actions/metadata-action/README.md
actions/metadata-action/config.schema.json
actions/metadata-action/dist/config.schema.json
actions/metadata-action/dist/index.js
actions/metadata-action/src/extractor.js
actions/metadata-action/src/index.js
actions/metadata-action/src/loader.js
actions/metadata-action/src/report.js

feat:  Improve logging throughout the metadata action and introduce a summary report feature that provides detailed insights into the metadata processing results. This enhancement includes better visibility into configuration loading and validation, as well as the ability to display a summary of the metadata used during execution.

feat: Enhance metadata action with detailed logging and summary report

---

.github/workflows/python-publish.yml

Added mandatory parameters:
gh_app_id and GH_APP_KEY

breaking-change: update python-publish.yml

---

actions/metadata-action/dist/index.js
actions/metadata-action/src/index.js

bug: Improve template handling by allowing more flexible key patterns and flatten the GitHub context in the run function for better data management. Remove unnecessary blank lines for cleaner code.

bug: Enhance template handling and improve GitHub context flattening

---

actions/maven-snapshot-deploy/action.yaml

Refine the GitHub Action for Maven by removing the alternative store parameter, updating the GITHUB_TOKEN reference, and adding GitHub server configuration to Maven settings.

feat: Update Maven GitHub Action configuration

---

actions/maven-release/action-script.sh
actions/maven-release/action.yaml

Added ${MVN_ARGS} to mvn release command

fix: update actions/maven-release/action-script.sh

---

actions/assets-action/dist/index.js
actions/assets-action/package-lock.json
actions/assets-action/package.json
actions/assets-action/src/assetsUploader.js
actions/assets-action/src/index.js

feat:
- Added @actions/glob as a dependency to facilitate file pattern matching.
- Updated assetUploader.js to set the GH_TOKEN environment variable.
- Enhanced index.js to use glob for matching files and directories based on provided patterns.
- Improved error handling and logging for file access issues.
- Adjusted the reporting of matched files for better clarity.
#217

feat: add glob dependency and enhance asset processing

---

.github/workflows/auto-assign-project-to-issue.yml

Added Auto-assign Project to issue from Netcracker/.github

feat: Added Auto-assign Project to issue

---

.github/workflows/re-npm-publish.yml
README.md

Renamed the npm-publish and removed extra logic

feat: Updated the npm_publish

---

actions/charts-values-update-action/action.yaml
actions/charts-values-update-action/image-versions-replace.py

When searching image version by regular expression, the action will not try to check if found version is SemVer.

feat: charts values update action

---

actions/docker-action/action.yml

Add functionality to the Docker action that generates and outputs the path and filename of a metadata file containing image details.

feat: Enhance Docker action to output metadata file details

---

README.md

Update release drafter workflow path in README
Update README file.
No issue
docs
(e.g., `docs`, `actions`, `workflows`).

docs: update release drafter workflow path in README

---

.github/workflows/re-security-scan.yml

Trivy an Grype will report issues with existing fix only.
Severity levels high (>=7.0 and <= 8.9) and critical (>=9.0)
`workflows`
https://github.com/borislavr/pgskipper-patroni/security/code-scanning
https://github.com/borislavr/pgskipper-patroni/actions/runs/18280629670

fix: Update Trivy severity levels and enhance Grype SARIF filtering logic
